CREATE TABLE CLIENTE( 
    RUT_CLIENTE NUMBER(11) NOT NULL, 
    DV CHAR(1), 
    PRIMER_NOMBRE VARCHAR2(250) NOT NULL, 
    SEGUNDO_NOMBRE VARCHAR2(250) NULL, 
    APELLIDO_PATERNO VARCHAR2(250) NOT NULL,  
    APELLIDO_MATERNO VARCHAR2(250) NULL, 
    DIRECCION VARCHAR2(250) NOT NULL, 
    FONO NUMBER NOT NULL, 
    CORREO VARCHAR2(250) NOT NULL, 
    COMUNA_ID NUMBER NOT NULL 
);

ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_PK PRIMARY KEY (rut_cliente);

CREATE TABLE Comuna(
    id_comuna NUMBER NOT NULL,
    nombre VARCHAR(250) NOT NULL,
    provincia_id NUMBER NOT NULL
)